### ISSUE TITLE
Won't send the messages 

### ISSUE THREAD

**Issue by Quizicle** [Kichi779/Twitch-Chat-Bot#1]
Now the script seems to be working fine. But the messages simply won't show in the chat.

I have made it so anyone can speak and they don't have to be verified. I am just confused

**Comment by memesaregood1** [comment]
Can confirm. Can connect and authorize with the IRC, but after sending PRIVMSG, the message does not appear in the regular chat.

**Comment by Quizicle** [comment]
> Can confirm. Can connect and authorize with the IRC, but after sending PRIVMSG, the message does not appear in the regular chat.

Hey it works now. You need to get oauths. Make sure the chat is not follower only and let's anyone speak

**Comment by memesaregood1** [comment]
I wouldn't have been able to authenticate without the tokens. The chat is not follower only, it's open for everyone. For some reason, I can only send messages to my own channel and noone else's.

I guess it's not the issue of the code now, but the Twitch issue that wasn't documented in their docs.

**Comment by Quizicle** [comment]
> I wouldn't have been able to authenticate without the tokens. The chat is not follower only, it's open for everyone. For some reason, I can only send messages to my own channel and noone else's.
> 
> I guess it's not the issue of the code now, but the Twitch issue that wasn't documented in their docs.

The oauths do break. Only 3 of mine actively work. I had to makr new ones. I found thst using temp mail worked amazingly as twitch disable accounts if they are all with the same email.

**Comment by memesaregood1** [comment]
You're right.

Indeed, a new account is able to send messages to other channels. It appears that Twitch disables accounts that have too many connections in a short period of time (which was the case for me).

**Comment by mercuryin** [comment]
I have just created 50 new twitch accounts and the oaths file is are already filled with the oaths numbers and the chat is not sending anything to the chat and I have already disabled all the twitch restrictions as no follower, etc. Any idea ?
